// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var localization = Localization.FromJson(jsonString);

namespace BattleEngineJsonCreation
{
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public partial class Localization
    {
        [JsonProperty("FileName")]
        public string FileName { get; set; }

        [JsonProperty("Original")]
        public string Original { get; set; }

        [JsonProperty("Commentary")]
        public string Commentary { get; set; }

        [JsonProperty("Name")]
        public string Name { get; set; }

        [JsonProperty("Localization")]
        public LocalizationClass LocalizationLocalization { get; set; }
    }

    public partial class LocalizationClass
    {
        [JsonProperty("CULTURE_EN_US")]
        public string CultureEnUs { get; set; }
    }

    public partial class Localization
    {
        public static List<Localization> FromJson(string json) => JsonConvert.DeserializeObject<List<Localization>>(json, Converter.Settings);
    }
}
