// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using BattleEngineJsonCreation;
//
//    var settings = Settings.FromJson(jsonString);

namespace BattleEngineJsonCreation
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Settings
    {
        [JsonProperty("BEDPath")]
        public string BedPath { get; set; }

        [JsonProperty("chassisDefpath")]
        public string ChassisDefpath { get; set; }

        [JsonProperty("mechDefPath")]
        public string MechDefPath { get; set; }

        [JsonProperty("GenerateFromchassisDef")]
        public bool GenerateFromchassisDef { get; set; }

        [JsonProperty("UpdateCSV")]
        public bool UpdateCSV { get; set; }

        [JsonProperty("BTInstallDir")]
        public string BtInstallDir { get; set; }

        [JsonProperty("LoadDefsFromMods")]
        public bool LoadDefsFromMods { get; set; }

        [JsonProperty("OutputDir")]
        public string OutputDir { get; set; }
    }

    public partial class Settings
    {
        public static Settings FromJson(string json) => JsonConvert.DeserializeObject<Settings>(json, Converter.Settings);
    }
}

