// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using BattleEngineJsonCreation;
//
//    var settings = Settings.FromJson(jsonString);

namespace BattleEngineJsonCreation
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Settings
    {
        [JsonProperty("BEDPath", NullValueHandling = NullValueHandling.Ignore)]
        public string BedPath { get; set; }

        [JsonProperty("chassisDefpath", NullValueHandling = NullValueHandling.Ignore)]
        public string ChassisDefpath { get; set; }

        [JsonProperty("mechDefPath", NullValueHandling = NullValueHandling.Ignore)]
        public string MechDefPath { get; set; }

        [JsonProperty("GenerateFromchassisDef", NullValueHandling = NullValueHandling.Ignore)]
        public bool GenerateFromchassisDef { get; set; }

        [JsonProperty("UpdateCSV", NullValueHandling = NullValueHandling.Ignore)]
        public bool UpdateCSV { get; set; }

        [JsonProperty("BTInstallDir", NullValueHandling = NullValueHandling.Ignore)]
        public string BtInstallDir { get; set; }

        [JsonProperty("LoadDefsFromMods", NullValueHandling = NullValueHandling.Ignore)]
        public bool LoadDefsFromMods { get; set; }

        [JsonProperty("OutputDir", NullValueHandling = NullValueHandling.Ignore)]
        public string OutputDir { get; set; }
    }

    public partial class Settings
    {
        public static Settings FromJson(string json) => JsonConvert.DeserializeObject<Settings>(json, Converter.Settings);
    }
}

